name:                raptor
version:             0.1.0.0
github:              "githubuser/raptor"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/raptor#readme>

dependencies:
- base >= 4.7 && < 5
- xml >= 1.3 && < 1.4
- req >= 1.0 && < 1.1
- text >= 1.2 && < 1.3
- data-default-class >= 0.1 && < 0.2

library:
  source-dirs: src

default-extensions:
- OverloadedStrings

executables:
  raptor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raptor

tests:
  raptor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raptor
